### PR TITLE
Fix Invalid/a tensor funccpp is broken and code cant compile

### LINKED ISSUE #27: Invalid: a_tensor_func.cpp is broken and code cant compile
**What & Where?**
a_tensor_func.cpp

**Why?**
- [x] Drop the "virtual" specifier; it is redundant.sonarqube(cpp:S3471)
- [x] invalid abstract return type for member function 'virtual Tensor<float> ExampleTensorFunction::derivative(const Tensor<float>&) const'GCC
- [x] Replace the use of "new" with an operation that automatically manages the memory.sonarqube(cpp:S5025)

**Suggestion**
Fix the GCC issue, you can also fix the suggestions given by the linter I use. Also, rename the file to example_tensor_func.cpp, In the original issue said there was supposed to be a cpp file as well but I have since then found out it's not needed for abstract classes, they can be declared in header files.

### PR DESCRIPTION
**Pull request by Breman402**
### Description
Made changes to the hpp file to make the functions use references instead and stop expecting a constant tensor. Changed the functions in the .cpp to reflect the changes made in the header file. Renamed the .cpp as requested as well. Also replaced the use of "new" with an operation that should automatically manage the memory.

The program compiles again.

I am not an expert when it comes to using references, but if I've interpreted the way that we want these functions to work it seems like making use of them might be an efficient thing to do.

### Issue
Fixes #27

### CODE REVIEW

File: src/include/a_tensor_func.hpp [hunk 1]
```diff
@@ -21,25 +20,23 @@ class TensorFunction {
 
     /// @brief Virtual destructor for TensorFunction.
     /// @details Ensures derived class destructors are called properly.
-    virtual ~TensorFunction() = default;
+    ~TensorFunction() = default;
```
Comment (ehmc123) [inline src/include/a_tensor_func.hpp:23]: Why is virtual not needed for the destructor? Could it not lead to undefined behaviors when deleting?

**Review by ehmc123 — COMMENTED** [review]
Good use of make_unique seems safer. Only wonder why virtual is not needed for the destructor?

File: src/include/a_tensor_func.hpp [hunk 2]
```diff
@@ -27,16 +27,16 @@ class TensorFunction {
...
     /// @param t the tensor to apply the function to.   
     /// @return the tensor after applying the function. 
-    virtual Tensor<T> func(const Tensor<T>& t) const = 0;
+    virtual Tensor<T>& func(Tensor<T>& t) const = 0;
 
     /// @brief Apply the derivative of the function to the tensor.
     /// @param t the tensor to apply the function to.
     /// @return the tensor after applying the derivative of the function.
-    virtual Tensor<T> derivative(const Tensor<T>& t) const = 0;
+    virtual Tensor<T>& derivative(Tensor<T>& t) const = 0;
```
Comment (ehmc123) [inline src/include/a_tensor_func.hpp:35]: Inputs could be constant if we still return tensor, so we could create a new tensor to then return. Might help with some issues with parallelization maybe?

**Review by ehmc123 — APPROVED** [review]
Looks good now! Keeping the input as a constant and returning a new tensor will probably be best for parallelization. Return by value instead of return by reference will probably be fine for now, size of the return object shouldn't be much of a concern with copy elision in c++17. Will merge, we can fix later if we believe issues will arise.
